services:
  - type: web
    name: BOLedit
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOL_BOT_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
